### ISSUE TITLE
Thorium Mod (Continued) and Human Alien Races Texture Issues

### ISSUE THREAD

**Issue by MrXarous** [emipa606/ThoriumMod#1]
User Ryuks2 reported in Discord and issue with Thorium Mod (Continued) when the Thorium Brotherhood caravan arrives at player's colony get red error log spam "Failed to find any textures at Things/Pawn/Humanlike/Bodies". Appears to be each pawn in the caravan. 

Using testing setup 

- Harmony
- Core
- Royalty
- Ideology
- Biotech
- HugsLib
- Human Alien Races
- Thorium mod (Continued)

Was able to replicate said issue and even dev mod forced a caravan of each type and errors populated in the log as described. Log can be found here: 
https://gist.github.com/HugsLibRecordKeeper/81f1ea20fd1487d8f56c066ffa25f7d3

Noted that also the pawns did have the missing texture "box" graphic as well. Any other information that is needed please let me know.

**Comment by emipa606** [comment]
Thanks to Zaljerem this is now fixed in 19444cf
